

 

  [[redirects]]
  from = "/api/*"
  to = "https://donationbloodapp.herokuapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[headers]]
for = "/"
[headers.values]
Access-Control-Allow-Origin = "*"